name: file_manager
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  draggable_scrollbar: ^0.0.4
  flutter:
    sdk: flutter
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  # Flutter 的一些动画
  flutter_spinkit: "^4.1.2"
  # 可拖拽的ListView
  # 状态管理
  provider: 5.0.0-nullsafety.3
  # svg图像
  flutter_svg: 0.20.0-nullsafety.3

  dio: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nightmare.file_manager
        pluginClass: FileManagerPlugin
      ios:
        pluginClass: FileManagerPlugin
  assets:
    - assets/icon/
